spring:
  application:
    name: spock-testcontainers
  datasource:
    name: postgres
    url: jdbc:postgresql://localhost:5432/${spring.datasource.name}
    username: ${spring.datasource.name}
    password: ${spring.datasource.name}